# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Accidentally Awake
author: Kelly Marie Gal
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Got caught up in a spiritual awakening? Same here. There is nothing more confusing, distressing, beautiful, and joyous than having your eyes open for the first time. But as wonderful as it is, it's a lonely journey. My voice, my words are commiseration as we brave this new life together, accidentally awake.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://accidentally-awake.com" # the base hostname & protocol for your site
# github_username:    jekyll
# instagram_username: jekyllrb
# twitter_username:   jekyllrb
paginate: 4
paginate_path: "/page/:num"
permalink: /:year-:month/:title
repository: katbratgal/jekyll-theme-libretto

# Build settings
markdown: kramdown

livereload: true
